In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape,a1.ndim,a1.dtype,type(a1)

((3,), 1, dtype('int32'), numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2.shape,a2.ndim,a2.dtype,type(a2)

((2, 3), 2, dtype('int32'), numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a3.shape,a3.ndim,a3.dtype,type(a3)

((2, 2, 3), 3, dtype('int32'), numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [7]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0,10,size=(7,2))
random_array

array([[7, 4],
       [7, 1],
       [2, 5],
       [0, 4],
       [8, 6],
       [9, 7],
       [0, 5]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array2 = np.random.random((3,5))
random_array2

array([[0.98568351, 0.20198944, 0.19268477, 0.19634775, 0.80891589],
       [0.61002376, 0.28771836, 0.54184082, 0.44450872, 0.77079329],
       [0.21097977, 0.14378675, 0.46809926, 0.76696542, 0.28349864]])

In [12]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array3 = np.random.randint(0,10,size=(4,6))
random_array3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array4 = np.random.randint(0,10,size=(3,7))
# Find the unique numbers in the array you just created
np.unique(random_array4)

array([0, 1, 2, 3, 4, 6, 8, 9])

In [14]:
# Find the 0'th index of the latest array you created
random_array4[0]

array([8, 0, 9, 2, 6, 3, 8])

In [15]:
# Get the first 2 rows of latest array you created
random_array4[:2]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
random_array4[:2,:2]

array([[8, 0],
       [2, 4]])

In [17]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array5 = np.random.randint(0,10,size=(3,5))
ones_array = np.ones((3,5))

In [18]:
# Add the two arrays together
random_array5+ones_array

array([[ 5.,  2.,  4.,  7.,  8.],
       [ 3.,  1.,  4.,  2.,  8.],
       [ 4.,  2.,  6.,  6., 10.]])

In [19]:
# Subtract the new array of ones from the other most recent array
random_array5-ones_array

array([[ 3.,  0.,  2.,  5.,  6.],
       [ 1., -1.,  2.,  0.,  6.],
       [ 2.,  0.,  4.,  4.,  8.]])

In [20]:
# Multiply the ones array with the latest array
random_array5*ones_array

array([[4., 1., 3., 6., 7.],
       [2., 0., 3., 1., 7.],
       [3., 1., 5., 5., 9.]])

In [21]:
# Take the latest array to the power of 2 using '**'
random_array5**2

array([[16,  1,  9, 36, 49],
       [ 4,  0,  9,  1, 49],
       [ 9,  1, 25, 25, 81]], dtype=int32)

In [22]:
# Do the same thing with np.square()
np.square(random_array5)

array([[16,  1,  9, 36, 49],
       [ 4,  0,  9,  1, 49],
       [ 9,  1, 25, 25, 81]], dtype=int32)

In [23]:
# Find the mean of the latest array using np.mean()
np.mean(random_array5)

3.8

In [24]:
# Find the maximum of the latest array using np.max()
np.max(random_array5)

9

In [25]:
# Find the minimum of the latest array using np.min()
np.min(random_array5)

0

In [26]:
# Find the standard deviation of the latest array
np.std(random_array5)

2.5612496949731396

In [27]:
# Find the variance of the latest array
np.var(random_array5)

6.5600000000000005

In [28]:
# Reshape the latest array to (3, 5, 1)
random_array5.reshape(3,5,1)

array([[[4],
        [1],
        [3],
        [6],
        [7]],

       [[2],
        [0],
        [3],
        [1],
        [7]],

       [[3],
        [1],
        [5],
        [5],
        [9]]])

In [29]:
# Transpose the latest array
random_array5.T

array([[4, 2, 3],
       [1, 0, 1],
       [3, 3, 5],
       [6, 1, 5],
       [7, 7, 9]])

In [30]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_array6 = np.random.randint(0,10,size=(3,3))
random_array7 = np.random.randint(0,10,size=(3,2))

In [31]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array6,random_array7)

array([[ 48,  33],
       [112, 127],
       [ 76,  70]])

In [32]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
random_array8 = np.random.randint(0,10,size=(3,3))
random_array9 = np.random.randint(0,10,size=(3,3))

In [33]:
# Compare the two arrays with '>'
random_array8>random_array9

array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True, False]])

In [34]:
# Compare the two arrays with '>='
random_array8>=random_array9

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False]])

In [35]:
# Find which elements of the first array are greater than 7
random_array8>7

array([[ True,  True,  True],
       [False,  True, False],
       [ True, False, False]])

In [36]:
# Which parts of each array are equal? (try using '==')
random_array8==random_array9

array([[False, False, False],
       [ True, False, False],
       [False, False, False]])

In [37]:
# Sort one of the arrays you just created in ascending order
np.sort(random_array8)

array([[8, 8, 9],
       [0, 6, 8],
       [0, 7, 8]])

In [38]:
# Sort the indexes of one of the arrays you just created
np.argsort(random_array8)

array([[1, 2, 0],
       [0, 2, 1],
       [2, 1, 0]], dtype=int64)