## Introduction to tensors

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.4.1'

In [4]:
# Create tensors with tf.constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# Check number of dimensions of tensors
scalar.ndim

0

In [7]:
vector = tf.constant([10,5])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  5])>

In [8]:
vector.ndim

1

In [14]:
# Create a matrix
matrix= tf.constant([[10,5],[3,6]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  5],
       [ 3,  6]])>

In [11]:
matrix.ndim

2

In [15]:
matrix2= tf.constant([[10,5],[3,6],[5,6]],dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  5.],
       [ 3.,  6.],
       [ 5.,  6.]], dtype=float16)>

In [16]:
matrix2.ndim

2

In [19]:
tensor= tf.constant([[[10,5],[3,6],[5,6]],[[1,2],[3,4],[6,1]]])
tensor

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[10,  5],
        [ 3,  6],
        [ 5,  6]],

       [[ 1,  2],
        [ 3,  4],
        [ 6,  1]]])>

In [20]:
tensor.ndim

3

In [21]:
# Create the same tensor with tf.Variable() and tf.constant()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [22]:
# To change any value in variable tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [30]:
# Create two random tensors 
random_1 = tf.random
random_2 = tf.random 
random_1 = random_1.normal(shape=(3, 2))
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

# Each time we run the cell we will get differenet values

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.6805261 ,  1.2624326 ],
        [-1.5070994 ,  0.40738115],
        [ 0.32432637,  0.6843706 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.97754955, -1.8175702 ],
        [-1.1545017 , -0.66723007],
        [-0.28364685,  0.48572356]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [32]:
# Seting the value of seed
# Create two random (but the same) tensors
random_3 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(42)
random_4 = random_4.normal(shape=(3, 2))

# Are they equal?
random_3, random_4, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [34]:
# Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Gets different results each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [50]:
# Shuffle in the same order every time

# Set the global random seed
tf.random.set_seed(42)

# Set the operation random seed
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [51]:
# Make a tensor of all ones
tf.ones(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [52]:
# Make a tensor of all zeros
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [55]:
# Converting a numpy array into tensor of desired shape
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
A = tf.constant(numpy_A,shape=[2, 4, 3]) # note: the shape total (2*4*3) has to match the number of elements in the array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]])>)

In [56]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [57]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [58]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [59]:
# Get the first 2 items of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [60]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [61]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [62]:
#Matrix Multiplication
#Base of the matrix should be same
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [63]:
#Also matmul can be written as @
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [65]:
tf.tensordot(tensor,tensor,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [67]:
tf.reshape(tensor, (4,1))

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[10],
       [ 7],
       [ 3],
       [ 4]])>

In [69]:
tf.transpose(tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  3],
       [ 7,  4]])>

In [70]:
# Create a new tensor with default datatype (int32)
C = tf.constant([1, 7])

In [72]:
# Changing the datatype of C
C=tf.cast(C,dtype=tf.float16)

In [73]:
C

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 7.], dtype=float16)>

In [74]:
#To get absolute values (ie. All positive)
D = tf.constant([-7, -10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [75]:
# Create a tensor with 50 random values between 0 and 100
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([80, 97, 87,  4, 80, 84, 79, 35, 22, 55, 23, 66, 83, 96, 86, 13,  9,
       29, 44, 90, 38, 46, 23, 14, 72, 88, 44, 69,  4, 15, 25, 20, 89, 79,
       67, 23, 80, 74, 49, 75, 49, 96, 44, 59, 27, 14, 73, 22, 38, 34])>

In [76]:
tf.reduce_max(E),tf.reduce_min(E),tf.reduce_mean(E),tf.reduce_sum(E)

(<tf.Tensor: shape=(), dtype=int32, numpy=97>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(), dtype=int32, numpy=52>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2612>)

In [77]:
# Getting positional max and min
tf.argmax(E),tf.argmin(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=1>,
 <tf.Tensor: shape=(), dtype=int64, numpy=3>)

In [78]:
# Find the maximum element position of F
print(f"The maximum value of E is at position: {tf.argmax(E).numpy()}") 
print(f"The maximum value of E is: {tf.reduce_max(E).numpy()}") 
print(f"Using tf.argmax() to index E, the maximum value of E is: {E[tf.argmax(E)].numpy()}")
print(f"Are the two max values the same (they should be)? {E[tf.argmax(E)].numpy() == tf.reduce_max(E).numpy()}")

The maximum value of E is at position: 1
The maximum value of E is: 97
Using tf.argmax() to index E, the maximum value of E is: 97
Are the two max values the same (they should be)? True


In [79]:
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [80]:
#To remove all 1 dimensions from tensor
squeezed_tensor = tf.squeeze(G)
squeezed_tensor.shape,squeezed_tensor.ndim

(TensorShape([50]), 1)

In [81]:
# Create a new tensor
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [84]:
# Square it
tf.square(H)

In [86]:
# Find the squareroot (will error), needs to be non-integer
H = tf.cast(H,dtype=tf.float32)
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [87]:
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>